### PR TITLE
[reconnect] fixes #1138

### LINKED ISSUE #1007: Auto reconnect doesn't work under certains circumstances
Hello,

When ready check is on and an MaxRetriesPerRequestError happens, a recoverFromFatalError is called in the ready check causing disconnect(true) to be called and will lead to abort to reconnection process.

This is leading us in a situation where express session associated to redisStore isn't working anymore.

a quick and dirty fix for us is to disable ready check or set MaxRetriesPerRequest to -1

Our case to test the bug:

ioredis express client connected as a standalone redis configuration to redis-ha chart with haproxy enabled and 3 redis/sentinel behind. (haproxy is routing all requests to the master node)
kill or scale to 0 haproxy.
ioredis is entering the autoreconnect loop (with retrystrategy)

Adding this stack to help : 
```
programname programname 2019-11-20T08:58:29.197Z ioredis:redis status[10.19.246.167:6379 (clientname)]: close -> reconnecting
programname programname 2019-11-20T08:58:29.197Z ioredis:connection reach maxRetriesPerRequest limitation, flushing command queue... v1
programname programname 2019-11-20T08:58:29.197Z ioredis:connection reach maxRetriesPerRequest limitation, flushing command queue... DONE v1
programname programname 2019-11-20T08:58:29.197Z ioredis:redis recoverFromFatalError MaxRetriesPerRequestError: Reached the max retries per request limit (which is 1). Refer to "maxRetriesPerRequest" option for details.
programname programname 2019-11-20T08:58:29.198Z ioredis:redis DISCONNECT CALLED v2 true
programname programname Trace
programname programname     at Redis.disconnect (/snapshot/programname/node_modules/ioredis/built/redis/index.js:323:10)
programname programname     at Redis.recoverFromFatalError (/snapshot/programname/node_modules/ioredis/built/redis/index.js:365:10)
programname programname     at /snapshot/programname/node_modules/ioredis/built/redis/event_handler.js:53:30
programname programname     at /snapshot/programname/node_modules/ioredis/built/redis/index.js:436:20
programname programname     at tryCatcher (/snapshot/programname/node_modules/standard-as-callback/built/utils.js:11:23)
programname programname     at promise.then (/snapshot/programname/node_modules/standard-as-callback/built/index.js:30:51)
programname programname     at process._tickCallback (internal/process/next_tick.js:68:7)

```

### LINKED ISSUE #1138: calling disconnect(true) multiple times
Hi!

I've noticed that calling the `disconnect(true)` sequentially multiple times actually cancels the re-connection process.

The issue resides in the `disconnect` method where the `clearTimeout` function is called regardless of whether or not the `reconnect` parameter is set to `true`:

```javascript
public disconnect(reconnect = false) {
  ...
  if (this.reconnectTimeout) { // <-- here we should check if reconnect is also false
    clearTimeout(this.reconnectTimeout);
    ....
  }
  ...
}
```

I've made a fix that I will introduce in a new PR following the opening of this issue.

Thank you for your time!

PS: this issue might be related to https://github.com/luin/ioredis/issues/1007.

### PR DESCRIPTION
**Pull request by alexandre-abrioux**
Hi,

This PR has been opened following the issue #1138.
It might also fix #1007 (not tested).

Thank you for your time!

### CODE REVIEW

File: lib/redis/index.ts [hunk 1]
```diff
@@ -278,10 +278,9 @@ Redis.prototype.connect = function (callback) {
 
     this.condition = {
       select: options.db,
-      auth:
-        options.username
-          ? [options.username, options.password]
-          : options.password,
+      auth: options.username
```
Comment (alexandre-abrioux) [inline lib/redis/index.ts:281]: this is a change made by prettier during husky pre-commit hook

File: lib/redis/index.ts [hunk 2]
```diff
@@ -278,10 +278,9 @@ Redis.prototype.connect = function (callback) {
...
+        ? [options.username, options.password]
+        : options.password,
```
Comment (alexandre-abrioux) [inline lib/redis/index.ts:283]: this is a change made by prettier during husky pre-commit hook

**Comment by luin** [comment]
Awesome! Good catch!
