### PR TITLE
fix(cluster): lazyConnect with pipeline

### LINKED ISSUE #1407: Cluster lazyConnect will not auto connect in pipeline/multi/enableAutoPipelining

### PR DESCRIPTION
**Pull request by jseagull**
this will fix #1407

### CODE REVIEW

File: lib/pipeline.ts [hunk 1]
```diff
@@ -241,6 +242,7 @@ Pipeline.prototype.execBuffer = deprecate(function () {
 Pipeline.prototype.exec = function (callback: CallbackFunction) {
   // Wait for the cluster to be connected, since we need nodes information before continuing
   if (this.isCluster && !this.redis.slots.length) {
+    if (this.redis.status === "wait") this.redis.connect();
```
Comment (TysonAndre) [inline lib/pipeline.ts:245]:
```suggestion
    if (this.redis.status === "wait") this.redis.connect().catch(noop);
```

I think that without the Promise.catch, there may be an UnhandledPromiseRejection that would terminate node processes with a `process.on('unhandledRejection')` listener that terminates.

Looks reasonable otherwise, but I'm not a maintainer

Comment (jseagull) [reply lib/pipeline.ts]: Added to all three location.

**Review by luin — APPROVED** [review]

**Comment by luin** [comment]
Thanks @jseagull @TysonAndre !
